### PR TITLE
update dependencies, and added test script

### PR DESCRIPTION
**Pull request by cxoltero**

### CODE REVIEW

**Comment by obuckley-kenzan** [comment]
Can one of the admins verify this patch?

**Comment by thescientist13** [comment]
ok to test

**Comment by thescientist13** [comment]
do we know if there are concerns with B.C. and passing through any config options from consumers?

**Comment by thescientist13** [comment]
resolved issue #29

**Comment by thescientist13** [comment]
looks like there are no major version bumps in `dependencies` here, so should be ok

**Pull request merged**
